//! Where this binary came from.
//!
//! The constant is generated by `build.rs` into `OUT_DIR` and included here
//! rather than read with `env!`, because `env!` expands in the crate where it
//! is written and `build-kit` is a different crate. See `build_kit`'s module
//! docs for why that matters.

include!(concat!(env!("OUT_DIR"), "/build_stamp.rs"));

use build_kit::{Install, Stamp};

/// The libraries this binary is made of, each reporting its own version.
///
/// Worth printing because they release separately: "gsnz 0.1.0" alone does not
/// say which `fsnz-api` was compiled in, and that is the part that breaks when
/// a supermarket changes its API.
const LIBRARIES: [(&str, &str); 7] = [
    ("gsnz-core", gsnz_core::VERSION),
    ("gsnz-ui", gsnz_ui::VERSION),
    ("cli-kit", cli_kit::VERSION),
    ("net-kit", net_kit::VERSION),
    ("fsnz-api", fsnz_api::VERSION),
    ("wwnz-api", wwnz_api::VERSION),
    ("build-kit", build_kit::VERSION),
];

pub fn stamp() -> &'static Stamp {
    &STAMP
}

/// `0.4.0 (abc1234 2026-01-01)` -- what `--version` prints.
///
/// Leaked once rather than rebuilt per call: clap wants a `&'static str`, and
/// a version string that lives as long as the process is not a leak worth
/// worrying about.
pub fn short_version() -> &'static str {
    static TEXT: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    TEXT.get_or_init(|| STAMP.short_version()).as_str()
}

/// `--version`: the whole provenance, plus the libraries and how this file got
/// where it is. `-V` keeps the short form.
pub fn long_version() -> &'static str {
    static TEXT: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    TEXT.get_or_init(|| {
        let path = build_kit::exe_path();
        // The install record lives under the state directory, which the
        // environment can move -- so this has to resolve it the same way the
        // rest of the program does.
        let install = state_dir().and_then(|paths| Install::current(&paths));
        let note = install.as_ref().map(|i| i.note("gsnz"));
        let mut text = STAMP.long_version(path.as_deref().and_then(|p| p.to_str()), note.as_ref());
        // One per line, aligned under the label column: seven of them comma-run
        // together is a wall, and the version is the part being looked for.
        let width = LIBRARIES.iter().map(|(n, _)| n.len()).max().unwrap_or(0);
        for (i, (name, version)) in LIBRARIES.iter().enumerate() {
            let label = if i == 0 { "libraries" } else { "" };
            text.push_str(&format!("\n{label:<11}{name:<width$}  {version}"));
        }
        text
    })
    .as_str()
}

fn state_dir() -> Option<net_kit::Paths> {
    let env = crate::env::Overrides::get();
    let mut paths = net_kit::Paths::defaults(crate::app::APP).ok()?;
    if let Some(dir) = &env.state_dir {
        paths = paths.with_state_dir(dir.clone());
    }
    Some(paths)
}
