//! Where this binary came from.
//!
//! The constant is generated by `build.rs` into `OUT_DIR` and included here
//! rather than read with `env!`, because `env!` expands in the crate where it
//! is written and `build-kit` is a different crate. See `build_kit`'s module
//! docs for why that matters.

include!(concat!(env!("OUT_DIR"), "/build_stamp.rs"));

/// `0.4.0 (abc1234 2026-01-01)` -- what `--version` prints.
///
/// Leaked once rather than rebuilt per call: clap wants a `&'static str`, and
/// a version string that lives as long as the process is not a leak worth
/// worrying about.
pub fn short_version() -> &'static str {
    static TEXT: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    TEXT.get_or_init(|| STAMP.short_version()).as_str()
}
